dist: trusty
sudo: false
cache:
  yarn: true
language: node_js
install:
  - yarn
env:
  global:
  - secure: Eu9IdOCMDNNtwjs0901xE53zsl6ExoZnGTo+8kOEy4qtZj0/PVCHPEfx3Ty9QFm5mSLVW6BVkJB4gHjZPuSKbMYrKIXwSFZcML4xYXMs7oWh2e9ulOVf8iSH/5MPj8+ib+UPcdwkJLhHXm3lIZs+PhySkIFbA045uPXVRT2Xusw=
  - secure: XCtfTIWdmyjp1ZDH9CPs7eXbOTAhfS031GWsru7rlOqPTWy0/RHL3BI5chBnn7Dh6ig34M6jQ2/4hcP/Qy+nPR9Gx44GF0jhEv3oEF5fyeSu3DsanKew3K0CIbnNRC4lEr/4qMaDkN4yLFeYCYpuvr0v2pyGpP9e+k7j3oqOmM8=
  - secure: DQyDbKYw2mShJViF/Y88W9L7ziKNodCdoN01bcXwtsACCZQ86vsVtQ2amQ6jUF0+y49FhbQRlycYzCCYLlt3zmYNIKAWk65+MoWqG1RojlQOWAgDo4HBKm7HWcohHLWNgqPSsbiBml5wN760Q1Imq1B9fKHj5cvowGwacJ2MEyo=
  - secure: MWJ5EUERWzRlBtBjSW8wchshqIL3HMKy+ZAfL7XUHtkDAS4TGBMgmtM5XyUEEx9q2Mwj4B1cbaQzIX7MANvNIPQj9qAQiy3/JgJt3305nYEHucYz+YGYvclZlYg371van8W6n+NImDxOiABkoIz2w8bn/kvhXtxCwS+/wDc66n0=
addons:
  browserstack:
    username: "treasuredataengi1"
    access_key:
      secure: "DIBSNeITB8FCEHLwPxZNpfx1HGy3BhGMmDyAwsHw6WTbfdrBrRwH70+0lfRiEOl39wFK+C88Ar2syC6A9NEej6RPIhCdukdzBduZUvUHc0OCvL6dUUbut6e76BsSKKtx0+XpFE3pA/pNE8F8yz18cG6rRQQmnfZ7y3WK5CBeTj4="
