dist: trusty
sudo: false
cache:
  yarn: true
language: node_js
env:
  global:
  - secure: Eu9IdOCMDNNtwjs0901xE53zsl6ExoZnGTo+8kOEy4qtZj0/PVCHPEfx3Ty9QFm5mSLVW6BVkJB4gHjZPuSKbMYrKIXwSFZcML4xYXMs7oWh2e9ulOVf8iSH/5MPj8+ib+UPcdwkJLhHXm3lIZs+PhySkIFbA045uPXVRT2Xusw=
  - secure: XCtfTIWdmyjp1ZDH9CPs7eXbOTAhfS031GWsru7rlOqPTWy0/RHL3BI5chBnn7Dh6ig34M6jQ2/4hcP/Qy+nPR9Gx44GF0jhEv3oEF5fyeSu3DsanKew3K0CIbnNRC4lEr/4qMaDkN4yLFeYCYpuvr0v2pyGpP9e+k7j3oqOmM8=
addons:
  browserstack:
    username: "dev@treasure-data.com"
    access_key:
      secure: "knd/zgP9vNnNj5AlYbHr4AK/B4A/V+FtQAGoE4IWnnD5VXf054LT4Nd0d7J23Zau77JjGDLwJmW2J+BZA/zCVmbyw0x0/JrFjPe7pdNGBWd4LLk8R/qqXl+3h6wJiN1IR6US0vBI+lUAFSnn7unfHd4i8/8suLVb1lpvSc0nP/E="
