ui: mocha-bdd

browsers:
  - name: chrome
    version: -2..latest
  - name: firefox
    version: latest
    version: -2..latest
  - name: safari
    version: 5..latest
  - name: ie
    version: 8..latest

concurrency: 1
