ui: tape
concurrency: 1
browsers:
  - name: chrome
    version: -2..latest
  - name: firefox
    version: 46 # 47 breaks zuul :(
    # version: -2..latest
  - name: safari
    version: 5..latest
  - name: ie
    version: 8..latest
